[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0.59"
bytes = "1.3.0"
tokio = { version = "1.23.0", features = ["full"] }
